### ISSUE TITLE
Google SSO phone number

### ISSUE THREAD

**Issue by mpavy-zelig** [bruno222/flex-mobile#12]
Hi. 
On our Twilio project, we're currently using Google SSO instead of a flex plugin SSO. 
We've made this choice because the whole IT infrastructure works with Google products, so it allow agents to login with the same email address as everywhere else. 
However, we've some issues when it comes to the mobile app, i don't understand how to get the phone number configured with the agent account, and how to link them with their twilio account. I tried to add '"phone_number":"+0123456789"' parameter to the agent attributes, and the same parameter inside the google agent account, but it never worked.

Sincerely,
Mpavy

**Comment by bruno222** [comment]
Hi @mpavy-zelig !

Here on Flex Mobile project, I am using a custom SSO project because I had to have a special way of authenticating the Agents on Mobile. 

The problem:

If the Agent does not open Flex Mobile app for more than 1 hour, his token will expire, so basically, every time the Agent opens Flex Mobile, he would need to login again, again, and every time. 

To solve:

I build [this SSO solution](https://github.com/bruno222/flex-mobile/tree/main/flex-plugin-sso) that saves a long-term token, allowing the agent to open Flex Mobile app without the need to re-authenticate every hour, for up to 7 days.

In your case:

You can still use Google SSO if you want to, ignore the installing steps of my custom SSO... Including the "phone_number" attribute within `worker.attribute`. The downside is that the agent will see, every time he opens the Flex mobile app, the Google authentication screens. If you are OK with that, all good.

Hope it helps!

**Comment by mpavy-zelig** [comment]
Hi @bruno222 ! 

Here, our agent we'll have a twilio account, so we decided they'll connect to the app using their account, to face the sso issue.
And so far, it seems to work pretty well.

Thank for the reply !
